from rest_framework.authentication import BaseAuthentication
from rest_framework.exceptions import AuthenticationFailed
from django.conf import settings
from django.contrib.auth import get_user_model
import jwt

User = get_user_model()


class ServiceTokenAuthentication(BaseAuthentication):
    """
    Authenticates TM-RAG service requests using a long-lived JWT.

    The service JWT is generated by the `create_rag_service_user` management command.
    It must belong to the dedicated service user.
    """

    keyword = "Bearer"

    def authenticate(self, request):
        auth_header = request.headers.get("Authorization")
        if not auth_header:
            return None

        try:
            prefix, token = auth_header.split()
            if prefix.lower() != self.keyword.lower():
                return None
        except ValueError:
            return None

        try:
            payload = jwt.decode(token, settings.SECRET_KEY, algorithms=["HS256"])
        except jwt.ExpiredSignatureError:
            raise AuthenticationFailed("Service token has expired.")
        except jwt.InvalidTokenError:
            raise AuthenticationFailed("Invalid service token.")

        user_id = payload.get("user_id")
        if not user_id:
            raise AuthenticationFailed("Invalid service token payload.")

        try:
            user = User.objects.get(pk=user_id, is_active=True)
        except User.DoesNotExist:
            raise AuthenticationFailed("Service user not found.")

        request.service_mode = True
        return (user, token)
